github: [theboringschool, codewithsudeep]
patreon: theboringschool
open_collective: theboringschool
ko_fi: theboringschool
tidelift: theboringschool
community_bridge: theboringschool
liberapay: theboringschool
issuehunt: theboringschool
otechie: theboringschool
